name: Check Rive-Android sub modules

on:
  # Let's check it when we push to master (we've just done something in rive-android, its a good time to see about this)
  push:
    branches:
      - master
  
  # 8am UTC every day
  schedule:
    - cron: '0 8 * * *'

  # Allow for manual pulling if there's some urgency
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run runtime version check
        uses: rive-app/github-actions-submodule-check@v8
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SUBMODULE_MAIN_BRANCH: main
          SUBMODULE_GIT_URL: https://github.com/rive-app/rive-runtime.git
